# Generated by Django 5.2.6 on 2025-09-23 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_file', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'telegram_accounts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('remember_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('payload', models.TextField()),
                ('last_activity', models.IntegerField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('telegram_account_id', models.BigIntegerField(db_index=True)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('username', models.TextField(blank=True, null=True)),
                ('oldest_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('oldest_message_time', models.DateTimeField(blank=True, null=True)),
                ('last_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_favorite', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'telegram_chats',
                'unique_together': {('id', 'telegram_account_id')},
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('telegram_account_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(db_index=True)),
                ('sender_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'telegram_messages',
                'unique_together': {('chat_id', 'telegram_account_id', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='TelegramSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('telegram_account_id', models.BigIntegerField(db_index=True)),
                ('last_message_id', models.BigIntegerField(blank=True, null=True)),
                ('oldest_message_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telegram_sync_state',
                'unique_together': {('chat_id', 'telegram_account_id')},
            },
        ),
    ]
