# Generated by Django 5.2.6 on 2025-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
