# Generated by Django 5.2.6 on 2025-09-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telegramaccount_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
