# Generated by Django 5.2.6 on 2025-09-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramaccount_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
