# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_telegramchat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]