# Generated by Django 5.2.7 on 2025-10-05 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_telegramMessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='session_file',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
